import type { LevelDefinition } from './LevelTypes'

export const STARTER_LEVELS: readonly LevelDefinition[] = [
  {
    id: 'starter-1',
    name: 'First Advance',
    tileSize: 32,
    enemySpawnPoints: [
      { x: 1, y: 1 },
      { x: 6, y: 1 },
      { x: 11, y: 1 },
    ],
    wave: [
      { type: 'basic', powerUpType: 'extra-life' },
      { type: 'basic', powerUpType: 'base-shield' },
      { type: 'fast', powerUpType: 'freeze-enemies' },
      { type: 'armored', powerUpType: 'weapon-upgrade' },
    ],
    map: [
      'SSSSSSSSSSSSS',
      'S...........S',
      'S.###.......S',
      'S.WW....GG..S',
      'S...........S',
      'S...........S',
      'S.....II....S',
      'S...........S',
      'S...........S',
      'S.....P.....S',
      'S.....B.....S',
      'S...........S',
      'SSSSSSSSSSSSS',
    ],
  },
  {
    id: 'starter-2',
    name: 'Canal Hold',
    tileSize: 32,
    enemySpawnPoints: [
      { x: 1, y: 1 },
      { x: 6, y: 1 },
      { x: 11, y: 1 },
    ],
    wave: [
      { type: 'fast', count: 2 },
      { type: 'basic', powerUpType: 'extra-life' },
      { type: 'armored', powerUpType: 'base-shield' },
    ],
    map: [
      'SSSSSSSSSSSSS',
      'S...........S',
      'S..#..S..#..S',
      'S..W..S..W..S',
      'S..W.....W..S',
      'S..###.###..S',
      'S.....G.....S',
      'S..###.###..S',
      'S...........S',
      'S.....P.....S',
      'S....#B#....S',
      'S...........S',
      'SSSSSSSSSSSSS',
    ],
  },
  {
    id: 'starter-3',
    name: 'Steel Cross',
    tileSize: 32,
    enemySpawnPoints: [
      { x: 1, y: 1 },
      { x: 6, y: 1 },
      { x: 11, y: 1 },
    ],
    wave: [
      { type: 'armored' },
      { type: 'fast', powerUpType: 'freeze-enemies' },
      { type: 'basic', count: 2 },
      { type: 'armored', powerUpType: 'weapon-upgrade' },
    ],
    map: [
      'SSSSSSSSSSSSS',
      'S...........S',
      'S..S..#..S..S',
      'S.....#.....S',
      'S###..#..###S',
      'S.....G.....S',
      'S..III.III..S',
      'S.....G.....S',
      'S###.....###S',
      'S.....P.....S',
      'S....#B#....S',
      'S...........S',
      'SSSSSSSSSSSSS',
    ],
  },
]
